# Generated by Django 6.0.1 on 2026-01-31 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_contributionwindow_contribution_penalty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateField()),
                ('unit_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('total_units', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='HoldingShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.DecimalField(decimal_places=4, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holding_shares', to='common.member')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holding_shares', to='common.investment')),
            ],
            options={
                'verbose_name': 'Holding share',
                'verbose_name_plural': 'Holding shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_record_type', models.CharField(choices=[('contribution', 'Contribution'), ('penalty', 'Penalty'), ('holding_share', 'Holding share'), ('asset_share', 'Asset share'), ('exit_request', 'Exit request'), ('buy_out', 'Buy out')], max_length=32)),
                ('original_record_id', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reversal',
                'verbose_name_plural': 'Reversals',
                'ordering': ['-created_at'],
            },
        ),
    ]
