# Generated by Django 6.0.1 on 2026-01-31 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_investment_holdingshare_reversal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('recorded_purchase_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('conversion_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_assets', to='common.investment')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-conversion_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percentage', models.DecimalField(decimal_places=4, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_shares', to='common.asset')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_shares', to='common.member')),
            ],
            options={
                'verbose_name': 'Asset share',
                'verbose_name_plural': 'Asset shares',
                'ordering': ['-created_at'],
            },
        ),
    ]
