# Generated by Django 6.0.1 on 2026-01-31 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_asset_assetshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal_valuation', models.DecimalField(decimal_places=4, max_digits=20)),
                ('valuation_inputs', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buy_outs_as_buyer', to='common.member')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_outs_as_seller', to='common.member')),
            ],
            options={
                'verbose_name': 'Buy out',
                'verbose_name_plural': 'Buy outs',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('queue_position', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('amount_entitled', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_requests', to='common.member')),
            ],
            options={
                'verbose_name': 'Exit request',
                'verbose_name_plural': 'Exit requests',
                'ordering': ['queue_position', '-requested_at'],
            },
        ),
    ]
